DROP DATABASE IF EXISTS `MVP`;

CREATE DATABASE `MVP`;

USE `MVP`;

DROP TABLE IF EXISTS `users`;
		
CREATE TABLE `users` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL DEFAULT NULL,
  `group` INTEGER NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS `bars`;
		
CREATE TABLE `bars` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL DEFAULT NULL UNIQUE,
  PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS `weeks`;
		
CREATE TABLE `weeks` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `week` DATE NULL DEFAULT NULL,
  `bar_id` INTEGER NULL DEFAULT NULL,
  `user_id` INTEGER NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

DROP TABLE IF EXISTS `groups`;
		
CREATE TABLE `groups` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL DEFAULT NULL UNIQUE,
  PRIMARY KEY (`id`)
);

ALTER TABLE `users` ADD FOREIGN KEY (group) REFERENCES `groups` (`id`);
ALTER TABLE `weeks` ADD FOREIGN KEY (bar_id) REFERENCES `bars` (`id`);
ALTER TABLE `weeks` ADD FOREIGN KEY (user_id) REFERENCES `users` (`id`);