CREATE DATABASE `MVP`;

USE `MVP`;
		
CREATE TABLE `users` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL DEFAULT NULL,
  `vote` INTEGER NULL DEFAULT NULL,
  `week` INTEGER NULL DEFAULT NULL,
  `group` INTEGER NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE `bars` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE `weeks` (
  `id` INTEGER NOT NULL AUTO_INCREMENT,
  `week` DATE NULL DEFAULT NULL,
  `winner` INTEGER NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE `groups` (
  `id` INTEGER NULL AUTO_INCREMENT DEFAULT NULL,
  `name` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
);

ALTER TABLE `users` ADD FOREIGN KEY (vote) REFERENCES `bars` (`id`);
ALTER TABLE `users` ADD FOREIGN KEY (week) REFERENCES `weeks` (`id`);
ALTER TABLE `users` ADD FOREIGN KEY (group) REFERENCES `groups` (`id`);
ALTER TABLE `weeks` ADD FOREIGN KEY (winner) REFERENCES `bars` (`id`);
